### ISSUE TITLE
Support for custom code first conventions

### ISSUE THREAD

**Issue by CyranoB** [tamasflamich/effort#18]
I'm getting the impression Effort doesn't support custom code first conventions.
I create a basic convention as following:
```C#
    public class DateTime2Convention : Convention
    {
        public DateTime2Convention()
        {
            this.Properties<DateTime>().Configure(c => c.HasColumnType("datetime2"));
        }
    }
```
and declaring it in OnModelCreating: 
```C#
modelBuilder.Conventions.Add(new DateTime2Convention()); 
```
Works fine with a real DB, but crashes with Effort:
```
Test Name:	TestXXX
Test FullName:	Domain.Data.Test.Model.EfXXXUnitTest.TestNumeroReference
Test Source:	EfXXXUnitTest.cs : line 57
Test Outcome:	Failed
Test Duration:	0:00:00.0342313

Result Message:	
Test method Domain.Data.Test.Model.EfXXXUnitTest.TestNumeroReference threw exception: 
System.InvalidOperationException: Sequence contains no matching element
Result StackTrace:	
at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at System.Data.Entity.Utilities.DbProviderManifestExtensions.GetStoreTypeFromName(DbProviderManifest providerManifest, String name)
   at System.Data.Entity.ModelConfiguration.Configuration.Properties.Primitive.PrimitivePropertyConfiguration.ConfigureColumn(EdmProperty column, EntityType table, DbProviderManifest providerManifest)
   at System.Data.Entity.ModelConfiguration.Configuration.Properties.Primitive.PrimitivePropertyConfiguration.Configure(EdmProperty column, EntityType table, DbProviderManifest providerManifest, Boolean allowOverride, Boolean fillFromExistingConfiguration)
   at System.Data.Entity.ModelConfiguration.Configuration.Properties.Primitive.PrimitivePropertyConfiguration.<>c__DisplayClass4.<Configure>b__3(Tuple`2 pm)
   at System.Data.Entity.Utilities.IEnumerableExtensions.Each[T](IEnumerable`1 ts, Action`1 action)
   at System.Data.Entity.ModelConfiguration.Configuration.Properties.Primitive.PrimitivePropertyConfiguration.Configure(IEnumerable`1 propertyMappings, DbProviderManifest providerManifest, Boolean allowOverride, Boolean fillFromExistingConfiguration)
   at System.Data.Entity.ModelConfiguration.Configuration.Types.StructuralTypeConfiguration.ConfigurePropertyMappings(IList`1 propertyMappings, DbProviderManifest providerManifest, Boolean allowOverride)
   at System.Data.Entity.ModelConfiguration.Configuration.ModelConfiguration.Configure(DbDatabaseMapping databaseMapping, DbProviderManifest providerManifest)
   at System.Data.Entity.DbModelBuilder.Build(DbProviderManifest providerManifest, DbProviderInfo providerInfo)
   at System.Data.Entity.DbModelBuilder.Build(DbConnection providerConnection)
   at System.Data.Entity.Internal.LazyInternalContext.CreateModel(LazyInternalContext internalContext)
   at System.Data.Entity.Internal.RetryLazy`2.GetValue(TInput input)
   at System.Data.Entity.Internal.LazyInternalContext.InitializeContext()
   at System.Data.Entity.Internal.InternalContext.GetEntitySetAndBaseTypeForType(Type entityType)
   at System.Data.Entity.Internal.Linq.InternalSet`1.Initialize()
   at System.Data.Entity.Internal.Linq.InternalSet`1.get_InternalContext()
   at System.Data.Entity.Infrastructure.DbQuery`1.System.Linq.IQueryable.get_Provider()
   at System.Linq.Queryable.Where[TSource](IQueryable`1 source, Expression`1 predicate)
   at Domain.Data.Model.EfXXXRepository.ListForNumeroReference(String NumeroReference) in Domain.Data\Model\EfXXXRepository.cs:line 22
   at Domain.Data.Test.Model.EfXXXUnitTest.TestForNumeroReference() in Domain.Data.Test\Model\EfXXXUnitTest.cs:line 58
```

**Comment by tamasflamich** [comment]
Hey @CyranoB - Sorry for the late response. Provider specific types are not supported by Effort and I should probably highlight this limitation in the docs. You can check [my sample project](http://1drv.ms/173VTu1) that tries to address this limitation.
