### ISSUE TITLE
AccessViolationException - Attempted to read or write protected memory

### ISSUE THREAD

**Issue by hicks86** [tamasflamich/effort#30]
Hello,
So I am using the Effort.EF6 (1.1.4) and NMemory(1.1.2) framework for my Unit Tests - now I have only recently returned to using Effort after deciding it was probably the best route for my situation. I have been using the framework for the past month without an issue, until yesterday morning I came across an:

> AccessViolationException was unhandled by user code
> 
> An exception of type 'System.AccessViolationException' occurred in NMemory.dll but was not handled in user code
> 
> Additional information: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

The particular case I refer to seems to happen when trying to perform a LINQ Where(x => x.) on one of the properties of my DbContext. I will check my other unit tests to see if it is just querying that it occurs on.

Now I have seen this issue before (https://effort.codeplex.com/discussions/632411) however it was never my laptop.

Any ideas on what is causing this?? It is just strange that it reappeared yesterday.

**Comment by Fistynuts** [comment]
We are seeing the same AccessViolationException when calling ToList() on a DbSet of our type "MilestoneType".

The stack trace is:

```
   at DataRow1..ctor(Nullable`1 Name, String OrderNumber, Nullable`1 InboundMilestone, Nullable`1 OutboundMilestone, Nullable`1 MilestoneUsage, Nullable`1 MilestoneChildTypeId, Nullable`1 Created, Nullable`1 CreatedBy, String Modified, Nullable`1 ModifiedBy, String Deleted, Nullable`1 DeletedBy, String )
   at lambda_method(Closure , MilestoneType )
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at NMemory.Execution.CommandExecutor.ExecuteQuery[T](IExecutionPlan`1 plan, IExecutionContext context, ITable[] tablesToLock, Boolean cloneEntities)
   at NMemory.Execution.CommandExecutor.ExecuteQuery[T](IExecutionPlan`1 plan, IExecutionContext context)
   at NMemory.Linq.TableQuery`1.GetEnumerator(IDictionary`2 parameters, Transaction transaction)
   at NMemory.Linq.TableQueryWrapper`1.GetEnumerator()
   at NMemory.Linq.TableQueryWrapper`1.System.Collections.IEnumerable.GetEnumerator()
   at Effort.Provider.EffortDataReader..ctor(IEnumerable result, Int32 recordsAffected, FieldDescription[] fields, DbContainer container)
   at Effort.Internal.CommandActions.QueryCommandAction.ExecuteDataReader(ActionContext context)
   at Effort.Provider.EffortEntityCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.<Reader>b__c(DbCommand t, DbCommandInterceptionContext`1 c)
   at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.Reader(DbCommand command, DbCommandInterceptionContext interceptionContext)
   at System.Data.Entity.Internal.InterceptableDbCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)
   at System.Data.Entity.Core.Objects.Internal.ObjectQueryExecutionPlan.Execute[TResultType](ObjectContext context, ObjectParameterCollection parameterValues)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__6()
   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__5()
   at System.Data.Entity.Infrastructure.DefaultExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<System.Collections.Generic.IEnumerable<T>.GetEnumerator>b__0()
   at System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at our code
```
Effort.EF6 1.1.4
NMemory 1.1.2
EF 6.1.3

The calling code is just

`var milestoneTypes = context.MilestoneTypes.ToList();`

This is a blocker for us using Effort for unit testing. Is there any additional information I can provide to help diagnose the problem?

**Comment by kennethscott** [comment]
I'm not sure if anyone's still watching the old codeplex post @hicks86 referenced, so I thought I'd also mention here that we are seeing a similar issue that seems to be triggered when we have Telerik's JustMock Profiler enabled.  It seems JustMock's use of the .NET Profiler API and Effort don't seem to play well together.  The free version of JustMock (or with it's profiler disabled) works fine with Effort.  Unfortunately though we use some of the advanced mocking functionality that requires it to be enabled.

**Comment by Fistynuts** [comment]
We also use the paid-for version of JustMock so that pretty much confirms the conflict.

**Comment by rhyshi** [comment]
We have JustMock installed however I'm not sure if its the Paid version - This could be conflict as mentioned. A few weeks after I had posted this question,  I made the decision to dump Effort and implement my own (very basic) way of testing our code that talks to EF (Using NSubstitute to create a Mock object of the  DbContext).

Out of curiosity, how are you guys testing this sort of code?

**Comment by kennethscott** [comment]
FYI - I opened a Telerik support ticket a couple days ago regarding this.  After a couple emails back-and-forth and having to send them an example project, I got this response from them this morning:

"We managed to reproduce the exception, it looks like there is a problem with our Code Weaver that breaks the Entity Framework. You correctly observed that enabling the profiler causes the issue.We have identified that it is a problem on our side and we will continue investigating it in a few days. We will keep you posted."

I'm still not holding my breath, but at least they've acknowledged it.

**Comment by kennethscott** [comment]
Update-  Telerik sent me a corrected pre-release build of JustMock this morning to try.  I am very happy to report that it seems to be working in our initial testing.  Our unit tests seem to be working fine even with the Profiler enabled.  

We will continue testing with Telerik, but hopefully this is something they can include in their next release.

**Comment by rhyshi** [comment]
Wow that is impressively quick.

I'm still a bit cautious about using Effort framework due to the amount of work it was to roll back. But like you said if this is included in the next release, maybe I'll venture back.

**Comment by Fistynuts** [comment]
Excellent, we'll try the new version of JustMock when it is released. Thanks for following this up!

**Comment by Fistynuts** [comment]
@kennethscott Sorry to resurrect this but did Telerik give you any idea of when this fix might make it into a public release?

**Comment by kennethscott** [comment]
@Fistynuts I actually just asked them that very question this past Tuesday (6/7).  This was their response:

> From: Telerik Admin
> Date: 6/7/2016 6:08:06 AM
> Hi,
> We will release it this or next week. Please, stay tuned.

Hopefully not much longer.  We aren't too crazy about committing the pre-release build they gave us either.  :smiley:

**Comment by kennethscott** [comment]
FYI, Telerik has posted a new Internal Build that includes this fix:

![image](https://cloud.githubusercontent.com/assets/823499/16307736/feede4fe-3927-11e6-8e2d-a65ff3582ca0.png)

**Comment by Fistynuts** [comment]
@kennethscott - I tried the new internal build and it does indeed fix the issue! Thanks again.
