### ISSUE TITLE
Issue when using second level cache

### ISSUE THREAD

**Issue by paddyfink** [tamasflamich/effort#36]
Hey,
I've installed EF seconde level cache https://efcache.codeplex.com/ and all my unit testing failed now This is on the result stack :

```
Result StackTrace:	
at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)
   at System.Data.Entity.Core.Objects.Internal.ObjectQueryExecutionPlan.Execute[TResultType](ObjectContext context, ObjectParameterCollection parameterValues)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__6()
   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__5()
   at System.Data.Entity.Infrastructure.DefaultExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<System.Collections.Generic.IEnumerable<T>.GetEnumerator>b__0()
   at System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.<GetElementFunction>b__1[TResult](IEnumerable`1 sequence)
   at System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.ExecuteSingle[TResult](IEnumerable`1 query, Expression queryRoot)
   at System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
   at System.Data.Entity.Internal.Linq.DbQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source, Expression`1 predicate)
   at MyProject.Migrations.SeedData.DefaultEditionsBuilder.CreateEditions() in C:\Users\Admin\Source\Repos\project\MyProject.EntityFramework\Migrations\SeedData\DefaultEditionsBuilder.cs:line 24
   at MyProject.Migrations.SeedData.DefaultEditionsBuilder.Build() in C:\Users\Admin\Source\Repos\project\MyProject.EntityFramework\Migrations\SeedData\DefaultEditionsBuilder.cs:line 19
   at MyProject.Migrations.SeedData.InitialDataBuilder.Create() in C:\Users\Admin\Source\Repos\project\MyProject.EntityFramework\Migrations\SeedData\InitialDataBuilder.cs:line 19
   at MyProject.Tests.AppTestBase.<>c.<.ctor>b__0_0(CrmDbContext context) in C:\Users\Admin\Source\Repos\project\Tests\MyProject.Tests\AppTestBase.cs:line 36
   at MyProject.Tests.AppTestBase.UsingDbContext(Action`1 action) in C:\Users\Admin\Source\Repos\project\Tests\MyProject.Tests\AppTestBase.cs:line 70
   at MyProject.Tests.AppTestBase..ctor() in C:\Users\Admin\Source\Repos\project\Tests\MyProject.Tests\AppTestBase.cs:line 34
   at MyProject.Tests.Authorization.Users.UserAppServiceTestBase..ctor() in C:\Users\Admin\Source\Repos\project\Tests\MyProject.Tests\Authorization\Users\UserAppServiceTestBase.cs:line 9
   at MyProject.Tests.Authorization.Users.UserAppService_GetUsers_Tests..ctor()
----- Inner Stack Trace -----
   at EFCache.QueryRegistrar.ContainsQuery(MetadataWorkspace workspace, String sql)
   at EFCache.CachingCommand.get_IsQueryAlwaysCached()
   at EFCache.CachingCommand.get_IsCacheable()
   at EFCache.CachingCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.<Reader>b__c(DbCommand t, DbCommandInterceptionContext`1 c)
   at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.Reader(DbCommand command, DbCommandInterceptionContext interceptionContext)
   at System.Data.Entity.Internal.InterceptableDbCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)
Result Message:	
System.Data.Entity.Core.EntityCommandExecutionException : An error occurred while executing the command definition. See the inner exception for details.
---- System.ArgumentNullException : Value cannot be null.
Parameter name: sql
```

How can I fix it please?

**Comment by tamasflamich** [comment]
Hi @paddyfink - Sorry for the late response, not sure whether this is still actual, but the problem is that the Effort provider doesn't use SQL strings for executing the database operations, but the cache provider seems to use the sql statements as cache keys.

There is probably no simple solution for this problem, so i would suggest to disable caching in test mode.
