### ISSUE TITLE
Exception when working with Automapper's ProjectTo (multiple collection mappings)

### ISSUE THREAD

**Issue by ProoM** [tamasflamich/effort#49]
Exception:

> Index was outside the bounds of the array.

Simplified code to replicate: 

`var measures = DataContext.People.ProjectTo<PersonModel>().ToArray();`

```
public class PersonEntity
{
       [Key]       
        public int Id { get; set; } 
        public string Name { get; set; } 
        public virtual ICollection<AccomplishmentEntity> Accomplishments{ get; set; } 
        public virtual ICollection<GoalEntity> Goals{ get; set; } 
}

public class PersonModel
{
        public int Id { get; set; } 
        public string Name { get; set; } 
        public IEnumerable<Accomplishment> Accomplishments{ get; set; } 
        public IEnumerable<Goal> Goals{ get; set; } 
}
```

```

public class PersonMapperProfile: Profile  
{  
        public PersonMapperProfile()  
        {  
                CreateMap<PersonEntity, PersonModel>()  
                .ForMember(dest => dest.Name, opt => opt.MapFrom(x => x.Name))  
                .ForMember(dest => dest.Accomplishments, opt => opt.MapFrom(x => x.Accomplishments))  
                .ForMember(dest => dest.Goals, opt => opt.MapFrom(x => x.Goals));  
        }  
}
```

The problem seems to lie in the fact the we're trying to project to multiple collections and Effort can't handle that. If we map any one of the collections while ignoring the other, everything works well. The simplest workaround for now seems to be to use `AutoMapper.Mapper.Map` instead of `ProjectTo` but I'm always hesitant to change production code to fit the limitations of tests. Entity Framework itself seems to know how to handle this pretty well, so this just fails in unit tests with Effort.

Looking for suggestions and feedback :)

StackTrace:

```
System.Data.Entity.Core.EntityCommandExecutionException : An error occurred while executing the command definition. See the inner exception for details.
  ----> System.IndexOutOfRangeException : Index was outside the bounds of the array.
   at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)
   at System.Data.Entity.Core.Objects.Internal.ObjectQueryExecutionPlan.Execute[TResultType](ObjectContext context, ObjectParameterCollection parameterValues)
   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClassb.<GetResults>b__9()
   at System.Data.Entity.Core.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<System.Collections.Generic.IEnumerable<T>.GetEnumerator>b__0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Crestone.ProjectCoulomb.Web.Handlers.Pqrs.GetMeasuresRequestHandler.Execute(Int32 caseId) in C:\Projects\<ProjectPath>\Handlers\Pqrs\GetMeasuresRequestHandler.cs:line 24
   at <ProjectName>.QaMeasures.QaMeasures.RegisterAndInsertIntoDb() in C:\Projects\<ProjectPath>\QaMeasures\QaMeasures.cs:line 50
--IndexOutOfRangeException
   at NMemory.Common.LinqJoinKeyHelper.CreateKeySelectors(Type outerType, Type innerType, IExpressionBuilder[] outerKeyCreator, IExpressionBuilder[] innerKeyCreator, LambdaExpression& outerKey, LambdaExpression& innerKey)
   at NMemory.Execution.Optimization.Rewriters.InnerJoinLogicalRewriter.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitArguments(IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at NMemory.Execution.Optimization.Rewriters.InnerJoinLogicalRewriter.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitArguments(IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at NMemory.Execution.Optimization.Rewriters.InnerJoinLogicalRewriter.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitArguments(IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at NMemory.Execution.Optimization.Rewriters.InnerJoinLogicalRewriter.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitArguments(IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at NMemory.Execution.Optimization.Rewriters.InnerJoinLogicalRewriter.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitArguments(IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at NMemory.Execution.Optimization.Rewriters.InnerJoinLogicalRewriter.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitArguments(IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at NMemory.Execution.Optimization.Rewriters.InnerJoinLogicalRewriter.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitArguments(IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at NMemory.Execution.Optimization.Rewriters.InnerJoinLogicalRewriter.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitArguments(IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at NMemory.Execution.Optimization.Rewriters.InnerJoinLogicalRewriter.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitArguments(IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at NMemory.Execution.Optimization.Rewriters.InnerJoinLogicalRewriter.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitArguments(IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at NMemory.Execution.Optimization.Rewriters.InnerJoinLogicalRewriter.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitArguments(IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at NMemory.Execution.Optimization.Rewriters.InnerJoinLogicalRewriter.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitArguments(IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at NMemory.Execution.Optimization.Rewriters.InnerJoinLogicalRewriter.VisitMethodCall(MethodCallExpression node)
   at NMemory.Execution.QueryCompilerBase.TransformExpression(Expression expression, ITransformationContext context, TransformationStepRecorder recorder)
   at NMemory.Execution.QueryCompilerBase.Compile[T](Expression expression)
   at NMemory.Linq.TableQuery`1.GetEnumerator(IDictionary`2 parameters, Transaction transaction)
   at NMemory.Linq.TableQueryWrapper`1.System.Collections.IEnumerable.GetEnumerator()
   at Effort.Provider.EffortDataReader..ctor(IEnumerable result, Int32 recordsAffected, FieldDescription[] fields, DbContainer container)
   at Effort.Internal.CommandActions.QueryCommandAction.ExecuteDataReader(ActionContext context)
   at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TInterceptionContext,TResult](Func`1 operation, TInterceptionContext interceptionContext, Action`1 executing, Action`1 executed)
   at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.Reader(DbCommand command, DbCommandInterceptionContext interceptionContext)
   at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)
```

**Comment by tamasflamich** [comment]
Hi ProoM - this seems like an NMemory bug for me. Based on the stack size, some sort of monstrous query is being compiled, so it might not be trivial to catch the cause. 

I don't really work with EF and .net anymore, so if I get a boring weekend I may give this a look.

**Comment by ProoM** [comment]
I've updated Effort to 1.2.0 and NMemory to 1.1.2 and it seems that this issue has resolved.

**Comment by tamasflamich** [comment]
Interesting, can't see any change that should have fixed that. Anyway, glad that it was resolved.
