### ISSUE TITLE
No Entity Framework provider found for the ADO.NET provider with invariant name 'Effort.Provider'. Make sure the provider is registered in the 'entityFramework' section of the application config file. See http://go.microsoft.com/fwlink/?LinkId=260882 for more information.

### ISSUE THREAD

**Issue by john1726** [tamasflamich/effort#53]
Presently, I am attempting to run a unit test using EFFORT, but I'm getting the following error.  This seems odd, because I clearly have `Effort.Provider.EffortProviderConfiguration.RegisterProvider();` in my test setup.  Please note that I am using the Effort and NMemory C# projects instead of installing with NuGet because I am trying to troubleshoot a `MultipleUniqueKeyFoundException` exception.  Does anyone have any suggestions?

```
System.InvalidOperationException was unhandled by user code
  HResult=-2146233079
  Message=No Entity Framework provider found for the ADO.NET provider with invariant name 'Effort.Provider'. Make sure the provider is registered in the 'entityFramework' section of the application config file. See http://go.microsoft.com/fwlink/?LinkId=260882 for more information.
  Source=EntityFramework
  StackTrace:
       at System.Data.Entity.Infrastructure.DependencyResolution.DefaultProviderServicesResolver.GetService(Type type, Object key)
       at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
       at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
       at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
       at System.Data.Entity.Infrastructure.DependencyResolution.RootDependencyResolver.GetService(Type type, Object key)
       at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
       at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
       at System.Data.Entity.Infrastructure.DependencyResolution.CompositeResolver`2.GetService(Type type, Object key)
       at System.Data.Entity.Infrastructure.DependencyResolution.DbDependencyResolverExtensions.GetService[T](IDbDependencyResolver resolver, Object key)
       at System.Data.Entity.Infrastructure.DefaultManifestTokenResolver.<>c__DisplayClass1.<ResolveManifestToken>b__0(Tuple`3 k)
       at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
       at System.Data.Entity.Utilities.DbConnectionExtensions.GetProviderInfo(DbConnection connection, DbProviderManifest& providerManifest)
       at System.Data.Entity.DbModelBuilder.Build(DbConnection providerConnection)
       at System.Data.Entity.Internal.LazyInternalContext.CreateModel(LazyInternalContext internalContext)
       at System.Data.Entity.Internal.RetryLazy`2.GetValue(TInput input)
       at System.Data.Entity.Internal.LazyInternalContext.InitializeContext()
       at System.Data.Entity.Internal.InternalContext.GetEntitySetAndBaseTypeForType(Type entityType)
       at System.Data.Entity.Internal.Linq.InternalSet`1.Initialize()
       at System.Data.Entity.Internal.Linq.InternalSet`1.get_InternalContext()
       at System.Data.Entity.Migrations.DbSetMigrationsExtensions.GetKeyProperties[TEntity](Type entityType, InternalSet`1 internalSet)
       at System.Data.Entity.Migrations.DbSetMigrationsExtensions.AddOrUpdate[TEntity](IDbSet`1 set, TEntity[] entities)
       at Cpr.Apps.Sam.Test.Model.Integration.Helpers.EffortEamEntitiesTestData.AddTestData(IEamEntities context) in C:\src\trunk\Cpr.Apps.Sam.Test.Model.Integration\Helpers\EffortEamEntitiesTestData.cs:line 37
       at Cpr.Apps.Sam.Test.Model.Integration.Helpers.IntegrationTest.IntegrationTestSetup() in C:\src\trunk\Cpr.Apps.Sam.Test.Model.Integration\Helpers\IntegrationTest.cs:line 51
  InnerException: 
```

**Comment by john1726** [comment]
Found a solution here, needed to install Effort.EF6 instead of just Effort: https://github.com/tamasflamich/effort/issues/14
