### ISSUE TITLE
System.NotSupportedException : Specified method is not supported.    at Effort.Provider.EffortCommand.ExecuteNonQuery()

### ISSUE THREAD

**Issue by john1726** [tamasflamich/effort#54]
Presently, in my unit test, I have:

```
        [Test]
        public void WillRetrieveTrackGradeIfItExists()
        {
            //Arrange
            InsertAssetCharacteristicAndValue(asset, AssetCharacteristicClassName.BRIDGE, AssetCharacteristicName.TRACK_GRADE, 11.23M);
            using (var cmd = ConnectionProviderBase.Connection.CreateCommand())
            {
                cmd.CommandText = "SELECT * FROM class";
                using (var reader = cmd.ExecuteReader())
                {
                    reader.HasRows.Should().BeTrue();
                }
            }

            //Act
            var results = Repository.FindMultipleByAsset(asset, AssetCharacteristicClassName.BRIDGE, AssetCharacteristicName.TRACK_GRADE).ToArray();

            //Assert
            results.Should().HaveCount(1);
            results[0].AssetCharacteristicName.Should().Be(AssetCharacteristicName.TRACK_GRADE.ToStorageValue<string>());
            results[0].NumericValue.Should().Be(11.23M);
        }
```

This results in the following function being called:

```
        private void InsertClassDefinition(string classId, string className)
        {
            using (var cmd = ConnectionProviderBase.Connection.CreateCommand())
            {
                var sql = @"INSERT INTO class ([CLASS_TYPE],[CLASS_NUM_INT],[CLASSNUM],[VALID_DATE_FROM],[VALID_DATE_TO]) VALUES('002',?,?,'1999-12-14','9999-12-31')";
                cmd.CommandText = sql;
                cmd.CommandType = CommandType.Text;
                CreateParameter(cmd, "@CLASS_NUM_INT", DbType.String, classId);
                CreateParameter(cmd, "@CLASS_NUM", DbType.String, className);
                
                cmd.ExecuteNonQuery();
            }
        }

        private void CreateParameter(DbCommand cmd, string parameterName, DbType dbType, object value)
        {
            IDbDataParameter parameter;

#if EFFORT 
            parameter = new EffortParameter();
#else 
            parameter = new SAParameter();
#endif
            parameter.ParameterName = parameterName;
            parameter.DbType = dbType;
            parameter.Value = value;
            cmd.Parameters.Add(parameter);
        }
```

When it reaches the `cmd.ExecuteNonQuery()`, then I get this exception:

> System.NotSupportedException : Specified method is not supported.
>    at Effort.Provider.EffortCommand.ExecuteNonQuery()
>    at Test.Model.Integration.Integration.Repositories.BaseAssetCharacteristicRepositoryTest.InsertClassDefinition(String classId, String className) in c:\Projects\Test.Model.Integration\Integration\Repositories\BaseAssetCharacteristicRepositoryTest.cs:line 115
>    at Test.Model.Integration.Integration.Repositories.BaseAssetCharacteristicRepositoryTest.InsertAssetCharacteristicAndValue(InspectionAsset asset, AssetCharacteristicClassName assetType, AssetCharacteristicName characteristicName, Decimal value) in c:\Projects\Test.Model.Integration\Integration\Repositories\BaseAssetCharacteristicRepositoryTest.cs:line 151
>    at Test.Model.Integration.Integration.Repositories.AssetCharacteristicRepositoryFindMultipleByAssetTests.WillRetrieveTrackGradeIfItExists() in c:\Projects\Test.Model.Integration\Integration\Repositories\AssetCharacteristicRepositoryFindMultipleByAssetTests.cs:line 42

Does anyone have any suggestions?  I have setup Effort basically according to this article: http://www.codeproject.com/Tips/1036630/Using-Effort-Entity-Framework-Unit-Testing-Tool

**UPDATE:**

One reason why it may not be working is because in the EF Database-First setup that I'm using, the EDMX file actually does not have a one-to-one relationship with classes to database tables for the class table.  It is actually a query view in EDMX that pulls data from several tables to populate a single C# class called AssetCharacteristic.  Ultimately there is no class table that the DB context points to, so that might explain why Effort cannot perform ExecuteNonQuery() against it.

**Comment by tamasflamich** [comment]
Hi @john1726 - Your code seems to use raw SQL statements that is not supported by Effort. It only supports the database independent [entity SQL](https://msdn.microsoft.com/en-us/library/bb738684(v=vs.110).aspx) statements, however, it doesn't seem to be popular among developers.

**Comment by john1726** [comment]
OK, if I try it the EntityParameter way, then I get this exception:

```
System.ArgumentException was unhandled by user code
  HResult=-2147024809
  Message=The provided parameter object is incompatible
  Source=Effort
  StackTrace:
       at Effort.Provider.EffortParameterCollection.Add(Object value)
       at Cpr.Apps.Sam.Test.Model.Integration.Integration.Repositories.BaseAssetCharacteristicRepositoryTest.CreateParameter(DbCommand cmd, String parameterName, DbType dbType, Object value) in c:\src\trunk\Cpr.Apps.Sam.Test.Model.Integration\Integration\Repositories\BaseAssetCharacteristicRepositoryTest.cs:line 31
       at Cpr.Apps.Sam.Test.Model.Integration.Integration.Repositories.BaseAssetCharacteristicRepositoryTest.InsertClassDefinition(String classId, String className) in c:\src\trunk\Cpr.Apps.Sam.Test.Model.Integration\Integration\Repositories\BaseAssetCharacteristicRepositoryTest.cs:line 105
       at Cpr.Apps.Sam.Test.Model.Integration.Integration.Repositories.BaseAssetCharacteristicRepositoryTest.InsertAssetCharacteristicAndValue(InspectionAsset asset, AssetCharacteristicClassName assetType, AssetCharacteristicName characteristicName, Decimal value) in c:\src\trunk\Cpr.Apps.Sam.Test.Model.Integration\Integration\Repositories\BaseAssetCharacteristicRepositoryTest.cs:line 146
       at Cpr.Apps.Sam.Test.Model.Integration.Integration.Repositories.AssetCharacteristicRepositoryFindMultipleByAssetTests.WillRetrieveTrackGradeIfItExists() in c:\src\trunk\Cpr.Apps.Sam.Test.Model.Integration\Integration\Repositories\AssetCharacteristicRepositoryFindMultipleByAssetTests.cs:line 50
  InnerException: 
```

Here is how I have updated the code:

```
        private void InsertClassDefinition(string classId, string className)
        {
            using (var cmd = ConnectionProviderBase.Connection.CreateCommand())
            {
                var sql = @"INSERT INTO EAM.TCLASS ([CLASS_TYPE],[CLASS_NUM_INT],[CLASSNUM],[VALID_DATE_FROM],[VALID_DATE_TO]) VALUES('002',@CLASS_NUM_INT,@CLASS_NUM,'1999-12-14','9999-12-31')";
                cmd.CommandText = sql;
                cmd.CommandType = CommandType.Text;
                //cmd.Parameters.Add("@CLASS_NUM_INT", SADbType.NVarChar).Value = classId;
                CreateParameter(cmd, "CLASS_NUM_INT", DbType.String, classId);
                
                //cmd.Parameters.Add("@CLASS_NUM", SADbType.NVarChar).Value = className;
                CreateParameter(cmd, "CLASS_NUM", DbType.String, className);
                
                cmd.ExecuteNonQuery();
            }
        }

        private void CreateParameter(DbCommand cmd, string parameterName, DbType dbType, object value)
        {
            var parameter = new EntityParameter();
            parameter.ParameterName = parameterName;
            parameter.DbType = dbType;
            parameter.Value = value;
            cmd.Parameters.Add(parameter);
        }
```

What am I missing?  TIA.
