### ISSUE TITLE
MigrationsException with IdentityModel 2.2.0: No MigrationSqlGenerator found for provider 'Effort.Provider'

### ISSUE THREAD

**Issue by anjdreas** [tamasflamich/effort#7]
According to [latest news](https://aspnetidentity.codeplex.com/workitem/1991) the IdentityModel 2.2 finally added a ctor overload without the CompiledModel parameter. However, running all the latest nugets (EF 6.1.2 + Effort.EF6 1.1.4 + identity model 2.2.0) I'm getting the below exception.

I tried adding ```SetSqlGenerator("Effort.Provider", new SqlServerMigrationSqlGenerator());``` to Configuration.cs ctor, but that left me with some incompatible provider exception.

I always seem to struggle trying to use Effort with the ApplicationDbContext that comes out of the box with ASP.net. Am I doing something wrong or is it simply not supported? Other contexts inheriting from DbContext work fine, but not when inheriting from IdentityDbContext<ApplicationUser>.

```
System.Data.Entity.Migrations.Infrastructure.MigrationsException : No MigrationSqlGenerator found for provider 'Effort.Provider'. Use the SetSqlGenerator method in the target migrations configuration class to register additional SQL generators.
   at System.Data.Entity.Migrations.DbMigrationsConfiguration.GetSqlGenerator(String providerInvariantName)
   at System.Data.Entity.Migrations.DbMigrator.GenerateStatements(IList`1 operations, String migrationId)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteOperations(String migrationId, VersionedModel targetModel, IEnumerable`1 operations, IEnumerable`1 systemOperations, Boolean downgrading, Boolean auto)
   at System.Data.Entity.Migrations.DbMigrator.ApplyMigration(DbMigration migration, DbMigration lastMigration)
   at System.Data.Entity.Migrations.DbMigrator.Upgrade(IEnumerable`1 pendingMigrations, String targetMigrationId, String lastMigrationId)
   at System.Data.Entity.Migrations.DbMigrator.EnsureDatabaseExists(Action mustSucceedToKeepDatabase)
   at System.Data.Entity.MigrateDatabaseToLatestVersion`2.InitializeDatabase(TContext context)
   at System.Data.Entity.Internal.InternalContext.PerformInitializationAction(Action action)
   at System.Data.Entity.Internal.InternalContext.PerformDatabaseInitialization()
   at System.Data.Entity.Internal.RetryAction`1.PerformAction(TInput input)
   at System.Data.Entity.Internal.LazyInternalContext.InitializeDatabaseAction(Action`1 action)
   at System.Data.Entity.Internal.InternalContext.GetEntitySetAndBaseTypeForType(Type entityType)
   at System.Data.Entity.Internal.Linq.InternalSet`1.Initialize()
   at System.Data.Entity.Internal.Linq.InternalSet`1.get_InternalContext()
   at System.Data.Entity.Internal.Linq.InternalSet`1.ActOnSet(Action action, EntityState newState, Object entity, String methodName)
   at System.Data.Entity.Internal.Linq.InternalSet`1.Add(Object entity)
   at System.Data.Entity.DbSet`1.Add(TEntity entity)
```

**Comment by anjdreas** [comment]
It seems calling ```db.Database.CreateIfNotExists()``` fixed it. The exception message just threw me off on what was actually wrong.

None of the tutorials or FAQ mention this, so I think adding a couple of getting started examples in the github readme would help a lot.

**Comment by Worthy7** [comment]
So.. What did you do again?

In my real app I have EF use 

`Database.SetInitializer(new MigrateDatabaseToLatestVersion<NewWebEdiDbContext,            Configuration>());`

To manage my migrations.

But I don't need this in my testing, where I use Effort instead of a real DB.

So, @anjdreas  what did you do again to make this work? call `db.Database.CreateIfNotExists()` where?

**Comment by anjdreas** [comment]
Oh man, I can't recall. This was so long ago. But I assume I called `CreateIfNotExists()` early in my tests, either once for a test class or per test - can't say for sure.
Also in tests, it's possible you can use `Database.SetInitializer(null)` or maybe not set a value at all, in order to disable migrations altogether.
