### ISSUE TITLE
Many to Many relationship error when deleting

### ISSUE THREAD

**Issue by nojan1** [tamasflamich/effort#84]
I have a database first setup looking like this.

![image](https://user-images.githubusercontent.com/3210085/31603988-2791e220-b262-11e7-9dec-eb6160ad2428.png)

In the scenario I have a single *Grupp* referencing a single *Objekt* which links to a single *Objektdata* through the *ObjektViaTillhorighet* navigation property. They all have there Id values set to 1 respectively.

Trying to delete the *Objektdata* as well as the *Objekt* using the below code.

```
var objektdata = db.Objektdata
                        .Include(x => x.ObjektViaRelation)
                        .Include(x => x.ObjektViaTillhorighet)
                        .Single(x => x.Id == objektdataId);

 int? objektId = objektdata.ObjektViaTillhorighet.FirstOrDefault()?.Id;
 if (objektId.HasValue)
  {
       var objekt = db.Objekt
                      .Include(x => x.ObjektdataViaRelation)
                      .Include(x => x.ObjektdataViaTillhorighet)
                      .Single(x => x.Id == objektId);

     if(!objekt.ObjektdataViaRelation.Any() && 
        (!objekt.ObjektdataViaTillhorighet.Any() || objekt.ObjektdataViaTillhorighet.All(x => x.Id == 
   objektdataId)))
         {
             db.Objekt.Remove(objekt);
         }
       }

 db.Objektdata.Remove(objektdata);
 db.SaveChanges();
```

Gives the following error:
```
System.Data.Entity.Infrastructure.DbUpdateException occurred
  HResult=0x80131501
  Message=An error occurred while saving entities that do not expose foreign key properties for their relationships. The EntityEntries property will return null because a single entity cannot be identified as the source of the exception. Handling of exceptions while saving can be made easier by exposing foreign key properties in your entity types. See the InnerException for details.
  Source=EntityFramework
  StackTrace:
   at System.Data.Entity.Internal.InternalContext.SaveChanges()
   at System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   at System.Data.Entity.DbContext.SaveChanges()

Inner Exception 1:
UpdateException: Unable to determine a valid ordering for dependent operations. Dependencies may exist due to foreign key constraints, model requirements, or store-generated values.

```

It seems the Many to Many aspect of the navigation property is confusing Effort since the same scenario works as intended when running against SQLServer.

**Comment by nojan1** [comment]
Nevermind manage to solve it. It seems Effort didn't correctly parse the Edmx-file.

Adding:
```
modelBuilder.Entity<Objekt>().HasMany<Objektdata>(x => x.ObjektdataViaRelation).WithMany(x => x.ObjektViaRelation);
modelBuilder.Entity<Objekt>().HasMany<Objektdata>(x => x.ObjektdataViaTillhorighet).WithMany(x => x.ObjektViaTillhorighet);
```

To *OnModelCreating* solved the issue.
